package eu.yeger.refunk.exception

internal class OverflowException : FunctionException("An overflow has occurred during the evaluation of a function")
